create  table mp_annovar
(
	av_chr     	varchar(10) not null,
	av_pos_start	int unsigned not null,
	av_pos_end	int unsigned not null,
	av_ref     	varchar(300) not null,
	av_alt     	varchar(300) not null,
	av_exonic	varchar(50),
	av_gene		varchar(500),
	av_consequence	varchar(50),
	av_refseq	varchar(1000),
	av_cosmic	varchar(1000),
	av_esp		varchar(10),
	av_dbsnp	varchar(50),
	av_1000g	varchar(10),
	av_cadd		varchar(10),
	av_cg69		varchar(50),
	av_nci60	varchar(50),
	av_clinvar	varchar(500),
	av_sift		varchar(10),
	av_sift_cnv	varchar(10),
	av_sift_cat	varchar(10),
	av_pp2hdiv	varchar(10),
	av_pp2hdiv_cat	varchar(10),
	av_pp2hvar	varchar(10),
	av_pp2hvar_cat	varchar(10),
	av_lrt		varchar(10),
	av_lrt_cnv	varchar(10),
	av_lrt_cat	varchar(10),
	av_mt		varchar(10),
	av_mt_cnv	varchar(10),
	av_mt_cat	varchar(10),
	av_ma		varchar(10),
	av_ma_cnv	varchar(10),
	av_ma_cat	varchar(10),
	av_fathmm	varchar(10),
	av_fathmm_cnv	varchar(10),
	av_fathmm_cat	varchar(10),
	av_metasvm	varchar(10),
	av_metasvm_cnv	varchar(10),
	av_metasvm_cat	varchar(10),
	av_metalr	varchar(10),
	av_metalr_cat	varchar(10),
	av_gerp		varchar(10),
	av_phylop	varchar(10),
	av_siphy	varchar(10),
	av_ens_variant	varchar(500)
) engine = myisam;

