CREATE TABLE mp_vep
(
  sample VARCHAR(100) NOT NULL,
  seqrun VARCHAR(100) NOT NULL,
  ens_variant VARCHAR(255) not null,
  chr VARCHAR(30) not null,
  pos VARCHAR(30) not null,
  allele VARCHAR(255) not null,
  ens_gene VARCHAR(30),
  ens_transcript VARCHAR(30),
  feature_type VARCHAR(30),
  consequence VARCHAR(255),
  cdna_position VARCHAR(30),
  cds_position VARCHAR(30),
  protein_position VARCHAR(30),
  amino_acids VARCHAR(255),
  codons VARCHAR(255),
  existing_variation VARCHAR(255),
  genename VARCHAR(30),
  domains TEXT,
  genedesc VARCHAR(255),
  ccds VARCHAR(50),
  ensp VARCHAR(50),
  cytoband VARCHAR(10),
  refseq_peptide VARCHAR(255),
  refseq_mrna VARCHAR(255),
  hgvsc VARCHAR(255),
  hgvsp VARCHAR(255),
  exon VARCHAR(30),
  cosmic_count VARCHAR(30),
  canonical CHAR(10),
  gene VARCHAR(50),
  gmaf VARCHAR(30),
  omim_ids TEXT,
  omim_count varchar(20),
  poly VARCHAR(30),
  sift VARCHAR(30),
  cadd_raw VARCHAR(30),
  cadd_phred VARCHAR(30),
  exac_af VARCHAR(30),
  clin_sig VARCHAR(100),
  biotype  VARCHAR(100),
  pubmed   TEXT,
  variant VARCHAR(255),
  refseq VARCHAR(30),
  cosmic VARCHAR(30),
  dbsnp  VARCHAR(30),
  hgvsg  VARCHAR(300)
) engine = myisam;
