CREATE TABLE ref_bic
(
  gene VARCHAR(30) NOT NULL,
  accession INT UNSIGNED NOT NULL,
  exon VARCHAR(30) NOT NULL,
  nt VARCHAR(30) NOT NULL,
  codon VARCHAR(30) NOT NULL,
  base_change VARCHAR(30) NOT NULL,
  aa_change VARCHAR(30) NOT NULL,
  designation VARCHAR(30) NOT NULL,
  hgvsc VARCHAR(200) NOT NULL,
  hgvsp Text NOT NULL,
  genotype VARCHAR(30) NOT NULL,
  dbsnp VARCHAR(30) NOT NULL,
  mutation_type VARCHAR(30) NOT NULL,
  consequence VARCHAR(30) NOT NULL,
  clinically_important VARCHAR(30) NOT NULL,
  depositor VARCHAR(100) NOT NULL,
  sample_source VARCHAR(255) NOT NULL,
  id_number VARCHAR(30) NOT NULL,
  number_reported VARCHAR(30) NOT NULL,
  g_or_s VARCHAR(30) NOT NULL,
  detection_method VARCHAR(100) NOT NULL,
  proband_tumour_type VARCHAR(30) NOT NULL,
  chr VARCHAR(30) NOT NULL,
  base_a VARCHAR(30) NOT NULL,
  base_c VARCHAR(30) NOT NULL,
  base_g VARCHAR(30) NOT NULL,
  base_t VARCHAR(30) NOT NULL,
  reference TEXT NOT NULL,
  contact VARCHAR(100) NOT NULL,
  notes VARCHAR(255) NOT NULL,
  created VARCHAR(30) NOT NULL,
  ethnicity VARCHAR(100) NOT NULL,
  nationality VARCHAR(100) NOT NULL,
  more_info VARCHAR(30) NOT NULL,
  variant VARCHAR(200) NOT NULL,
  hgvsg VARCHAR(200) NOT NULL,
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);
