CREATE TABLE ref_clinvar
(
  chr VARCHAR(2) NOT NULL,
  pos_start INT UNSIGNED NOT NULL,
  pos_end INT UNSIGNED NOT NULL,
  clinvar_id INT UNSIGNED NOT NULL,
  rgbcolor VARCHAR(30) NOT NULL,
  hyperlink VARCHAR(200) NOT NULL,
  clinvar_accession VARCHAR(30) NOT NULL,
  clinvar_ageofonset VARCHAR(100) NOT NULL,
  clinvar_clinicalsignificance VARCHAR(100) NOT NULL,
  clinvar_diseasename VARCHAR(200) NOT NULL,
  clinvar_molecularconsequence VARCHAR(100) NOT NULL,
  clinvar_origin VARCHAR(100) NOT NULL,
  clinvar_prevalence VARCHAR(255) NOT NULL,
  clinvar_referenceid INT UNSIGNED NOT NULL,
  clinvar_reviewstatus VARCHAR(100) NOT NULL,
  feature VARCHAR(255) NOT NULL,
  hgmdacc VARCHAR(30) NOT NULL,
  hgvs VARCHAR(255) NOT NULL,
  omim VARCHAR(30) NOT NULL,
  orpha VARCHAR(30) NOT NULL,
  rsid VARCHAR(30) NOT NULL,
  hgnc VARCHAR(30) NOT NULL,
  ensembl VARCHAR(30) NOT NULL,
  entrez VARCHAR(30) NOT NULL,
  uniprot VARCHAR(30) NOT NULL,
  variant VARCHAR(255) NOT NULL,
  hgvsc VARCHAR(255) NOT NULL,
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);
