CREATE TABLE ref_kconfab
(
  familyid INT UNSIGNED NOT NULL,
  bic VARCHAR(200) NOT NULL,
  hgvs VARCHAR(200) NULL,
  effect VARCHAR(10) NOT NULL,
  gene VARCHAR(30) NULL,
  hgvsc VARCHAR(200) NULL,
  variant VARCHAR(200) NULL,
  hgvsg VARCHAR(200) NULL,
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);
