CREATE TABLE ref_cosmic
(
  gene			VARCHAR(40) NOT NULL,
  accession		VARCHAR(30) NOT NULL,
  hgnc			VARCHAR(30)	NULL,
  sample		VARCHAR(30) NOT NULL,
  id_sample		INT UNSIGNED NOT NULL,
  id_tumour		INT UNSIGNED NOT NULL,
  site			VARCHAR(200) NOT NULL,
  site_sub		VARCHAR(200) NOT NULL,
  hist		 	VARCHAR(200) NOT NULL,
  hist_sub 		VARCHAR(200) NOT NULL,
  genome_screen VARCHAR(1) NOT NULL,
  cosmicid		VARCHAR(15) NOT NULL,
  hgvsc			VARCHAR(100) NULL,
  hgvsp			VARCHAR(100) NULL,
  muttyp		VARCHAR(100) NULL,
  zygosity		VARCHAR(10) NULL,
  ncbi36_pos	VARCHAR(30) NULL,
  ncbi36_strand	VARCHAR(1) NULL,
  pos			VARCHAR(30) NULL,
  strand 		VARCHAR(1) NULL,
  somatic_sts	VARCHAR(50) NULL,
  pubmed		VARCHAR(20) NULL,
  sample_src	VARCHAR(50) NOT NULL,
  origin		VARCHAR(50) NOT NULL,
  comments		VARCHAR(300) NULL,
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);
