CREATE TABLE ref_iarc
(
  mutation_id INT UNSIGNED NOT NULL,
  mut_id INT UNSIGNED NOT NULL,
  hg18_chr17_coordinates INT UNSIGNED NOT NULL,
  exonintron VARCHAR(10) NOT NULL,
  genomic_nt INT UNSIGNED NOT NULL,
  codon_number INT UNSIGNED NOT NULL,
  description VARCHAR(23) NOT NULL,
  c_description VARCHAR(34) NOT NULL,
  g_description VARCHAR(48) NOT NULL,
  g_description_hg19 VARCHAR(49) NULL,
  wt_nucleotide VARCHAR(3) NOT NULL,
  mutant_nucleotide VARCHAR(2) NOT NULL,
  splice_site VARCHAR(12) NOT NULL,
  cpg_site VARCHAR(3) NOT NULL,
  vartype VARCHAR(14) NOT NULL,
  mut_rate VARCHAR(30) NULL,
  wt_codon VARCHAR(7) NOT NULL,
  mutant_codon VARCHAR(7) NOT NULL,
  wt_aa VARCHAR(7) NOT NULL,
  mutant_aa VARCHAR(8) NOT NULL,
  protdescription VARCHAR(15) NOT NULL,
  mut_rateaa VARCHAR(30) NULL,
  effect VARCHAR(9) NOT NULL,
  structural_motif VARCHAR(26) NOT NULL,
  putative_stop INT UNSIGNED NOT NULL,
  sample_name VARCHAR(25) NOT NULL,
  sample_id INT UNSIGNED NOT NULL,
  sample_source VARCHAR(16) NOT NULL,
  tumor_origin VARCHAR(24) NOT NULL,
  topography VARCHAR(78) NOT NULL,
  short_topo VARCHAR(24) NOT NULL,
  topo_code VARCHAR(7) NOT NULL,
  sub_topography VARCHAR(74) NOT NULL,
  morphology VARCHAR(77) NOT NULL,
  morpho_code VARCHAR(7) NOT NULL,
  grade VARCHAR(25) NULL,
  stage VARCHAR(18) NULL,
  tnm VARCHAR(10) NULL,
  p53_ihc VARCHAR(8) NOT NULL,
  add_info VARCHAR(178) NULL,
  individual_id INT UNSIGNED NOT NULL,
  sex VARCHAR(2) NULL,
  age VARCHAR(10) NULL,
  ethnicity VARCHAR(26) NULL,
  geo_area VARCHAR(32) NULL,
  country VARCHAR(26) NOT NULL,
  development VARCHAR(22) NOT NULL,
  population VARCHAR(26) NOT NULL,
  region VARCHAR(26) NOT NULL,
  tp53polymorphism VARCHAR(37) NULL,
  germline_mutation VARCHAR(28) NOT NULL,
  family_history VARCHAR(53) NULL,
  tobacco VARCHAR(24) NOT NULL,
  alcohol VARCHAR(18) NOT NULL,
  exposure VARCHAR(42) NOT NULL,
  infectious_agent VARCHAR(27) NOT NULL,
  ref_id INT UNSIGNED NOT NULL,
  pubmed VARCHAR(10) NOT NULL,
  exclude_analysis VARCHAR(6) NOT NULL,
  variant VARCHAR(300),
  gene VARCHAR(30) NOT NULL,
  transcript VARCHAR(30) NOT NULL,
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);
