CREATE TABLE ref_hgmdimputed
(
  chr VARCHAR(10) NOT NULL,
  pos_start INT UNSIGNED NOT NULL,
  pos_end INT UNSIGNED NOT NULL,
  hgmdimp_id VARCHAR(30) NOT NULL,
  rgbcolor VARCHAR(30) NOT NULL,
  hyperlink VARCHAR(200) NOT NULL,
  hgmdacc VARCHAR(30) NOT NULL,
  mutationtype VARCHAR(10) NOT NULL,
  varianttype VARCHAR(10) NOT NULL,
  nucleotidechange VARCHAR(10) NOT NULL,
  hgvs VARCHAR(200) NOT NULL,
  disease VARCHAR(200) NOT NULL,
  confidence VARCHAR(10) NOT NULL,
  pmid TEXT NOT NULL,
  omim VARCHAR(10) NOT NULL,
  codon_change VARCHAR(10) NOT NULL,
  aminoacid_change VARCHAR(10) NOT NULL,
  codon_number INT UNSIGNED NOT NULL,
  comments VARCHAR(200) NOT NULL,
  genomic_sequence VARCHAR(200) NOT NULL,
  pmid_notes TEXT NOT NULL,
  pmid_citation_type VARCHAR(200) NOT NULL,
  ensembl VARCHAR(30) NOT NULL,
  entrez VARCHAR(30) NOT NULL,
  hgnc VARCHAR(30) NOT NULL,
  uniprot VARCHAR(200) NOT NULL,
  feature VARCHAR(200) NOT NULL,
  variant VARCHAR(200) NOT NULL,
  hgvsc VARCHAR(200) NOT NULL,
  hgvsp VARCHAR(200) NOT NULL,
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);
